[package]
name = "cursed_os"
version = "0.1.0"
edition = "2018"
authors = ["Joaquin Schere <owner@jschere.com>", "v1peridae <me@v1peridae.me>"]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]
bootloader = "0.9.8"


[[bin]]
name= "cursed_os"
