[package]
name = "cursed_os"
version = "0.1.0"
edition = "2018"
authors = ["Joaquin Schere <owner@jschere.com>", "Louisa M <me@v1peridae.me>"]

[dependencies]
bootloader = { version = "0.9.8", features = ["map_physical_memory"]}
volatile = "0.2.6"
spin = "0.5.2"
x86_64 = "0.15.2"
pic8259 = "0.10.1"
pc-keyboard = "0.7.0"
linked_list_allocator = "0.9.0"
sha2 = { version = "0.10", default-features = false, features = ["force-soft"] }

[profile.dev]
debug = true
opt-level = 0

[profile.release]
debug = true
opt-level = "s"


[dependencies.lazy_static]
version = "1.0"
features = ["spin_no_std"]

[[bin]]
name= "cursed_os"

[package.metadata.bootimage]
run-args  = ["-device", "isa-debug-exit,iobase=0xf4,iosize=0x04"]
test-args = ["-device", "isa-debug-exit,iobase=0xf4,iosize=0x04"]
